export const RECEIVE_MERCHANTS = 'RECEIVE_MERCHANTS';
export const UPDATE_MERCHANT = 'UPDATE_MERCHANT';
export const REMOVE_MERCHANT = 'REMOVE_MERCHANTS';
export const ADD_TO_MERCHANT = 'ADD_TO_MERCHANT';
